### ISSUE TITLE
Done button fails to save after an electrode has been created, then erased

### ISSUE THREAD

**Issue by pierremegevand** [HumanNeuronLab/ERWiN#1]
In reconstructing a patient with 11 S-EEG electrodes, I ran into an issue when attempting to use the "Done" button after I had mistakenly created a 12th electrode, then erased it by lowering the electrode count back to 11. The error message visible in the MATLAB command line window mentioned that there was an unrecognized field 'Electrode12' (unfortunately, I forgot to copy the whole error message). The .mgrid file was not created.

**Comment by jonathanmonney** [comment]
The callback function donePushed.m looped over all electrodes with information stored in the structure "widget.fig.UserData". Once an electrode is created, its information is stored in here and will not be removed even if the number of electrodes is lowered afterwards. This is so that if the number of electrodes is reduced by error, the information remains in memory.
**The code has been amended to loop exclusively over the number of electrodes that appears on the spinner, which resolves the issue.**

_Important note: the autosave "xxx_erwin.m" file retains the information from deleted electrodes. It is therefore possible to retrieve their location even after closing ERWiN by reloading the autosave file._
